### PR TITLE
Change a couple committee

### PR DESCRIPTION
**Pull request by DonPablo99**
That's from my new branch

### CODE REVIEW

**Comment by dolanmiu** [comment]
Can you name: `IMG_4148.JPG` to a more appropriate name

thanks

**Comment by DonPablo99** [comment]
Done! Sorry for that

**Comment by dolanmiu** [comment]
I have a feeling this wont work because in the `commitee.json` it is `"damodara.jpg"`, but the file is called `"damodara.JPG"`

Can you change one or the other

**Comment by DonPablo99** [comment]
For some reason it is 'jpg' in my local but shows as 'JPG' on Github ¯\_(ツ)_/¯ . I'll try to change both

**Comment by dolanmiu** [comment]
good stuff! approved and merged

**Pull request merged**
